package com.huawei.clouds.openrewrite.fastjson.internal;

public final class JacksonJsonSupport {
    private static final String BASE_HELPER_PACKAGE = "com.huawei.clouds.openrewrite.fastjson";
    private static final String HELPER_SIMPLE_NAME = "JacksonJson";

    private final FastjsonMigrationConfiguration configuration;

    private static final String TEMPLATE_STUB = """
            package com.huawei.clouds.openrewrite.fastjson;

            import com.fasterxml.jackson.core.type.TypeReference;
            import com.fasterxml.jackson.databind.JsonNode;
            import com.fasterxml.jackson.databind.node.ArrayNode;
            import com.fasterxml.jackson.databind.node.ObjectNode;
            import java.util.List;

            public final class JacksonJson {
                public static String toJson(Object value) { return null; }
                public static byte[] toJsonBytes(Object value) { return null; }
                public static <T> T fromJson(String json, Class<T> type) { return null; }
                public static <T> T fromJson(byte[] json, Class<T> type) { return null; }
                public static <T> T fromJson(String json, TypeReference<T> type) { return null; }
                public static <T> List<T> fromJsonList(String json, Class<T> type) { return null; }
                public static JsonNode readTree(String json) { return null; }
                public static JsonNode readTree(byte[] json) { return null; }
                public static ObjectNode readObject(String json) { return null; }
                public static ObjectNode readObject(byte[] json) { return null; }
                public static ArrayNode readArray(String json) { return null; }
                public static ObjectNode emptyObject() { return null; }
                public static ObjectNode objectFrom(Object value) { return null; }
                public static ArrayNode emptyArray() { return null; }
                public static ArrayNode arrayFrom(Object value) { return null; }
                public static <T extends JsonNode> T toTree(Object value) { return null; }
                public static <T> T convertValue(Object value, Class<T> type) { return null; }
                public static <T> List<T> convertList(Object value, Class<T> type) { return null; }
                public static Object get(Object node, Object key) { return null; }
                public static String getString(Object node, Object key) { return null; }
                public static Integer getInteger(Object node, Object key) { return null; }
                public static int getIntValue(Object node, Object key) { return 0; }
                public static Long getLong(Object node, Object key) { return null; }
                public static long getLongValue(Object node, Object key) { return 0; }
                public static Boolean getBoolean(Object node, Object key) { return null; }
                public static boolean getBooleanValue(Object node, Object key) { return false; }
                public static Double getDouble(Object node, Object key) { return null; }
                public static double getDoubleValue(Object node, Object key) { return 0; }
                public static ObjectNode getObjectNode(Object node, Object key) { return null; }
                public static ArrayNode getArrayNode(Object node, Object key) { return null; }
                public static <T> T getObject(Object node, Object key, Class<T> type) { return null; }
                public static Object put(Object node, Object key, Object value) { return null; }
                public static boolean add(Object node, Object value) { return false; }
                public static Object remove(Object node, Object key) { return null; }
                public static boolean containsKey(Object node, Object key) { return false; }
            }
            """;

    private static final String HELPER_SOURCE = """
            package com.huawei.clouds.openrewrite.fastjson;

            import com.fasterxml.jackson.core.JsonProcessingException;
            import com.fasterxml.jackson.core.type.TypeReference;
            import com.fasterxml.jackson.databind.DeserializationFeature;
            import com.fasterxml.jackson.databind.JsonNode;
            import com.fasterxml.jackson.databind.ObjectMapper;
            import com.fasterxml.jackson.databind.json.JsonMapper;
            import com.fasterxml.jackson.databind.node.ArrayNode;
            import com.fasterxml.jackson.databind.node.JsonNodeFactory;
            import com.fasterxml.jackson.databind.node.ObjectNode;

            import java.io.IOException;
            import java.util.List;

            /**
             * Jackson facade generated by the OpenRewrite Fastjson migration recipe.
             * It keeps JSON failures unchecked, matching Fastjson's calling convention.
             */
            public final class JacksonJson {
                private static final ObjectMapper MAPPER = JsonMapper.builder()
                        .findAndAddModules()
                        .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                        .build();

                private JacksonJson() {
                }

                public static String toJson(Object value) {
                    try {
                        return MAPPER.writeValueAsString(value);
                    } catch (JsonProcessingException e) {
                        throw failure("serialize JSON", e);
                    }
                }

                public static byte[] toJsonBytes(Object value) {
                    try {
                        return MAPPER.writeValueAsBytes(value);
                    } catch (JsonProcessingException e) {
                        throw failure("serialize JSON bytes", e);
                    }
                }

                public static <T> T fromJson(String json, Class<T> type) {
                    try {
                        return MAPPER.readValue(json, type);
                    } catch (IOException e) {
                        throw failure("deserialize JSON", e);
                    }
                }

                public static <T> T fromJson(byte[] json, Class<T> type) {
                    try {
                        return MAPPER.readValue(json, type);
                    } catch (IOException e) {
                        throw failure("deserialize JSON bytes", e);
                    }
                }

                public static <T> T fromJson(String json, TypeReference<T> type) {
                    try {
                        return MAPPER.readValue(json, type);
                    } catch (IOException e) {
                        throw failure("deserialize generic JSON", e);
                    }
                }

                public static <T> List<T> fromJsonList(String json, Class<T> elementType) {
                    try {
                        return MAPPER.readValue(json, MAPPER.getTypeFactory()
                                .constructCollectionType(List.class, elementType));
                    } catch (IOException e) {
                        throw failure("deserialize JSON array", e);
                    }
                }

                public static JsonNode readTree(String json) {
                    try {
                        return MAPPER.readTree(json);
                    } catch (IOException e) {
                        throw failure("read JSON tree", e);
                    }
                }

                public static JsonNode readTree(byte[] json) {
                    try {
                        return MAPPER.readTree(json);
                    } catch (IOException e) {
                        throw failure("read JSON tree", e);
                    }
                }

                public static ObjectNode readObject(String json) {
                    return requireObject(readTree(json));
                }

                public static ObjectNode readObject(byte[] json) {
                    return requireObject(readTree(json));
                }

                public static ArrayNode readArray(String json) {
                    return requireArray(readTree(json));
                }

                public static ObjectNode emptyObject() {
                    return JsonNodeFactory.instance.objectNode();
                }

                public static ObjectNode objectFrom(Object value) {
                    return requireObject(MAPPER.valueToTree(value));
                }

                public static ArrayNode emptyArray() {
                    return JsonNodeFactory.instance.arrayNode();
                }

                public static ArrayNode arrayFrom(Object value) {
                    return requireArray(MAPPER.valueToTree(value));
                }

                public static <T extends JsonNode> T toTree(Object value) {
                    return MAPPER.valueToTree(value);
                }

                public static <T> T convertValue(Object value, Class<T> type) {
                    return MAPPER.convertValue(value, type);
                }

                public static <T> List<T> convertList(Object value, Class<T> elementType) {
                    return MAPPER.convertValue(value, MAPPER.getTypeFactory()
                            .constructCollectionType(List.class, elementType));
                }

                public static Object get(Object node, Object key) {
                    return toJavaValue(child(node, key));
                }

                public static String getString(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : value.asText();
                }

                public static Integer getInteger(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : value.asInt();
                }

                public static int getIntValue(Object node, Object key) {
                    Integer value = getInteger(node, key);
                    return value == null ? 0 : value;
                }

                public static Long getLong(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : value.asLong();
                }

                public static long getLongValue(Object node, Object key) {
                    Long value = getLong(node, key);
                    return value == null ? 0L : value;
                }

                public static Boolean getBoolean(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : value.asBoolean();
                }

                public static boolean getBooleanValue(Object node, Object key) {
                    return Boolean.TRUE.equals(getBoolean(node, key));
                }

                public static Double getDouble(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : value.asDouble();
                }

                public static double getDoubleValue(Object node, Object key) {
                    Double value = getDouble(node, key);
                    return value == null ? 0D : value;
                }

                public static ObjectNode getObjectNode(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : requireObject(value);
                }

                public static ArrayNode getArrayNode(Object node, Object key) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : requireArray(value);
                }

                public static <T> T getObject(Object node, Object key, Class<T> type) {
                    JsonNode value = child(node, key);
                    return missing(value) ? null : MAPPER.convertValue(value, type);
                }

                public static Object put(Object node, Object key, Object value) {
                    ObjectNode object = requireObject(asNode(node));
                    String field = String.valueOf(key);
                    JsonNode previous = object.get(field);
                    object.set(field, MAPPER.valueToTree(value));
                    return toJavaValue(previous);
                }

                public static boolean add(Object node, Object value) {
                    requireArray(asNode(node)).add(MAPPER.valueToTree(value));
                    return true;
                }

                public static Object remove(Object node, Object key) {
                    JsonNode tree = asNode(node);
                    JsonNode removed;
                    if (tree.isObject()) {
                        removed = ((ObjectNode) tree).remove(String.valueOf(key));
                    } else if (tree.isArray() && key instanceof Number) {
                        removed = ((ArrayNode) tree).remove(((Number) key).intValue());
                    } else {
                        return null;
                    }
                    return toJavaValue(removed);
                }

                public static boolean containsKey(Object node, Object key) {
                    JsonNode tree = asNode(node);
                    return tree.isObject() && tree.has(String.valueOf(key));
                }

                private static JsonNode child(Object node, Object key) {
                    JsonNode tree = asNode(node);
                    if (tree.isObject()) {
                        return tree.get(String.valueOf(key));
                    }
                    if (tree.isArray() && key instanceof Number) {
                        return tree.get(((Number) key).intValue());
                    }
                    return null;
                }

                private static JsonNode asNode(Object value) {
                    return value instanceof JsonNode ? (JsonNode) value : MAPPER.valueToTree(value);
                }

                private static ObjectNode requireObject(JsonNode value) {
                    if (value != null && value.isObject()) {
                        return (ObjectNode) value;
                    }
                    throw new IllegalArgumentException("Expected a JSON object");
                }

                private static ArrayNode requireArray(JsonNode value) {
                    if (value != null && value.isArray()) {
                        return (ArrayNode) value;
                    }
                    throw new IllegalArgumentException("Expected a JSON array");
                }

                private static boolean missing(JsonNode value) {
                    return value == null || value.isNull() || value.isMissingNode();
                }

                private static Object toJavaValue(JsonNode value) {
                    return missing(value) ? null : MAPPER.convertValue(value, Object.class);
                }

                private static IllegalArgumentException failure(String operation, Exception cause) {
                    return new IllegalArgumentException("Unable to " + operation, cause);
                }
            }
            """;

    public JacksonJsonSupport(FastjsonMigrationConfiguration configuration) {
        this.configuration = configuration;
    }

    public String helperFqn() {
        return configuration.helperPackage() + "." + HELPER_SIMPLE_NAME;
    }

    public String helperRelativePath() {
        return configuration.helperPackage().replace('.', '/') + "/" + HELPER_SIMPLE_NAME + ".java";
    }

    public String templateStub() {
        return withConfiguredPackage(TEMPLATE_STUB);
    }

    public String helperSource() {
        return withConfiguredPackage(HELPER_SOURCE);
    }

    private String withConfiguredPackage(String source) {
        return source.replace(
                "package " + BASE_HELPER_PACKAGE + ";",
                "package " + configuration.helperPackage() + ";"
        );
    }
}
