package com.huawei.clouds.openrewrite.fsextra;

import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.Tree;
import org.openrewrite.TreeVisitor;
import org.openrewrite.marker.Markers;
import org.openrewrite.marker.SearchResult;
import org.openrewrite.text.PlainText;
import org.openrewrite.text.PlainTextVisitor;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Marks exact fs-extra Yarn and pnpm lockfile package keys. */
public final class FindFsExtraTextLockRisks extends Recipe {
    private static final Pattern ENTRY = Pattern.compile(
            "(?m)^[ \\t]*[\"']?/?(fs-extra)(?=@|/|:)");

    @Override
    public String getDisplayName() {
        return "Find fs-extra Yarn and pnpm lockfile risks";
    }

    @Override
    public String getDescription() {
        return "Marks exact fs-extra lock entries that must be regenerated by the repository package manager.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return new PlainTextVisitor<ExecutionContext>() {
            @Override
            public PlainText visitText(PlainText text, ExecutionContext ctx) {
                PlainText visited = super.visitText(text, ctx);
                if (!FsExtraSupport.isLockfile(visited.getSourcePath())) return visited;
                String source = visited.getText();
                Matcher matcher = ENTRY.matcher(source);
                List<PlainText.Snippet> snippets = new ArrayList<>();
                int cursor = 0;
                while (matcher.find()) {
                    int start = matcher.start(1);
                    int end = matcher.end(1);
                    if (start > cursor) snippets.add(new PlainText.Snippet(
                            Tree.randomId(), Markers.EMPTY, source.substring(cursor, start)));
                    snippets.add(SearchResult.found(new PlainText.Snippet(Tree.randomId(), Markers.EMPTY,
                                    matcher.group(1)),
                            "Regenerate this lockfile; versions, resolved artifacts, integrity, dependency snapshots, and package-manager metadata must come from the owning package manager"));
                    cursor = end;
                }
                if (snippets.isEmpty()) return visited;
                if (cursor < source.length()) snippets.add(new PlainText.Snippet(
                        Tree.randomId(), Markers.EMPTY, source.substring(cursor)));
                return visited.withText("").withSnippets(snippets);
            }
        };
    }
}
