package com.huawei.clouds.openrewrite.antvx6;

import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.Tree;
import org.openrewrite.TreeVisitor;
import org.openrewrite.marker.Markers;
import org.openrewrite.marker.SearchResult;
import org.openrewrite.text.PlainText;
import org.openrewrite.text.PlainTextVisitor;

import java.util.ArrayList;
import java.util.List;

/** Marks X6 entries in Yarn and pnpm lockfiles without fabricating integrity data. */
public final class FindAntvX6TextLockRisks extends Recipe {
    @Override
    public String getDisplayName() {
        return "Find AntV X6 Yarn and pnpm lockfile risks";
    }

    @Override
    public String getDescription() {
        return "Marks @antv/x6 lockfile entries that must be regenerated by the repository's package manager.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return new PlainTextVisitor<ExecutionContext>() {
            @Override
            public PlainText visitText(PlainText text, ExecutionContext ctx) {
                PlainText visited = super.visitText(text, ctx);
                if (!AntvX6Support.isLockfile(visited.getSourcePath())) return visited;
                String source = visited.getText();
                List<PlainText.Snippet> snippets = new ArrayList<>();
                int cursor = 0;
                int scan = 0;
                int match;
                while ((match = source.indexOf(AntvX6Support.PACKAGE, scan)) >= 0) {
                    scan = match + AntvX6Support.PACKAGE.length();
                    if (!isPackageBoundary(source, match)) continue;
                    if (match > cursor) snippets.add(new PlainText.Snippet(
                            Tree.randomId(), Markers.EMPTY, source.substring(cursor, match)));
                    snippets.add(SearchResult.found(new PlainText.Snippet(Tree.randomId(), Markers.EMPTY,
                                    AntvX6Support.PACKAGE),
                            "Regenerate this lockfile with its owning package manager; versions, peer snapshots, resolved artifacts, and integrity cannot be safely synthesized"));
                    cursor = match + AntvX6Support.PACKAGE.length();
                }
                if (snippets.isEmpty()) return visited;
                if (cursor < source.length()) snippets.add(new PlainText.Snippet(
                        Tree.randomId(), Markers.EMPTY, source.substring(cursor)));
                return visited.withText("").withSnippets(snippets);
            }

            private boolean isPackageBoundary(String source, int start) {
                int end = start + AntvX6Support.PACKAGE.length();
                if (start > 0) {
                    char before = source.charAt(start - 1);
                    if (Character.isLetterOrDigit(before) || before == '_' || before == '-') return false;
                }
                if (end < source.length()) {
                    char after = source.charAt(end);
                    if (Character.isLetterOrDigit(after) || after == '_' || after == '-' ||
                        after == '.' || after == '/') return false;
                }
                return true;
            }
        };
    }
}
